# -*- coding: utf-8 -*-
"""predictionfunc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13d68hWnZLAoPjX4s4pxYb3YPQwL3UHrO
"""

import gzip
import json
import pickle

import pandas as pd
# Create wrangle function
def wrangle(filename):
    with gzip.open(filename, "r") as f:
        data = json.load(f)

    #dict to dataframe, set index
    df = pd.DataFrame().from_dict(data["observations"]).set_index("id")
    return df

def make_predictions(data_filepath, model_filepath):
    # Wrangle JSON file
    X_test = wrangle(data_filepath)
    # Load model
    with open(model_filepath, "rb") as f:
        model = pickle.load(f)
    # Generate predictions
    y_test_pred = model.predict(X_test)
    # Put predictions into Series with name "bankrupt", and same index as X_test
    y_test_pred = pd.Series(y_test_pred, index = X_test.index, name = "bankrupt")
    return y_test_pred